#Artificial Neural Network

Importing the Libraries

In [31]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [32]:
tf.__version__

'2.15.0'

#Part 1 - Data Preprocessing

Importing the dataset

In [33]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[: , 3:13].values
y = dataset.iloc[ : ,13].values

In [34]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


#Encoding Categorical data

Label Encoding the 'Gender' column

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [36]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the 'Geography' column

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
# dummy variables moves to 1st column .
# France = 1.0 0.0 0.0
# Spain = 0.0 0.0 1.0
# Germany = 0.0 1.0 0.0
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting dataset into Training set and Test set

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

Feature Scaling
*(It is compulsory to apply Feature Scaling in DEEP LEARNING) *

In [39]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 : Building the ANN

Initializing the ANN

In [40]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first Hidden layer

In [41]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu')) # relu = Rectifier function

Adding the second hidden layer

In [42]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

Adding the output layer

In [43]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid')) # o/p layer activation function = sigmoid

# Part 3 : Training the ANN

Compiling the ANN


In [44]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
# For Binary classification || loss = binary_crossentropy || activation = sigmoid
# For categorical/non-binary classification || loss = categorical_crossentropy || activation = softmax

Training the ANN on training set

In [49]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 200)
# fit is used to Train any model in ML/DL

Epoch 1/200
250/250 [==============================] - 1s 3ms/step - loss: 0.3307 - accuracy: 0.8636
Epoch 2/200
250/250 [==============================] - 1s 2ms/step - loss: 0.3303 - accuracy: 0.8643
Epoch 3/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3302 - accuracy: 0.8649
Epoch 4/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3305 - accuracy: 0.8640
Epoch 5/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3300 - accuracy: 0.8652
Epoch 6/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3301 - accuracy: 0.8639
Epoch 7/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3296 - accuracy: 0.8645
Epoch 8/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3300 - accuracy: 0.8644
Epoch 9/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3300 - accuracy: 0.8635
Epoch 10/200
250/250 [==============================] - 0s 2ms/step - loss: 0.3290 - accura

# Part 4 : Making the predictions and evaluating the model

Predicting the result of a single observation

In [50]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5 )

1/1 [==============================] - 0s 38ms/step
[[False]]


Predicting the Test set results


In [51]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion Matrix

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1519   76]
 [ 199  206]]


0.8625